# Get Information About Schools (GIAS)

This notebook combines data downloaded from GIAS (https://get-information-schools.service.gov.uk/Downloads).

Further information can be found in the README.md in the edubase data folder

In [2]:
# Import libraries
import numpy as np
import pyodbc
import pandas as pd
import logging
import datetime
from datetime import datetime
import glob
from pathlib import Path
import os
import re
import random
from utils.connection_utils import connect_to_postgres

# Set display options for the notebook
pd.set_option('display.max_colwidth', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', 2000)
# pd.options.display.max_columns = None

from warnings import filterwarnings
filterwarnings("ignore", category=UserWarning, message='.*pandas only supports SQLAlchemy connectable.*')

# Clear previous logging configuration and configure a new one
for handler in logging.root.handlers[:]:
    logging.root.removeHandler(handler)

logging.basicConfig(level=logging.INFO,
                    format='%(asctime)s %(levelname)s %(message)s',
                    handlers=[logging.StreamHandler(), logging.FileHandler("notebook_log.log")])

logger = logging.getLogger(__name__)

In [3]:
# Get current working directory
dir_code = os.getcwd()
print("Current working directory:", dir_code)

# Define directory where data are stored, starting from your home directory
home = Path.home()
dir_data = home / 'OneDrive - Ambition Institute' / 'code' / 'DfE_data' / 'data' / 'get-information-about-schools'
print("Data directory:", dir_data)

# Change directory
if dir_data.exists():
    os.chdir(dir_data)
    print(f"Changed working directory to: {Path.cwd()}")
else:
    print(f"Directory does not exist: {dir_data}")

Current working directory: C:\Users\stefanie.meliss\OneDrive - Ambition Institute\code\DfE_data
Data directory: C:\Users\stefanie.meliss\OneDrive - Ambition Institute\code\DfE_data\data\get-information-about-schools
Changed working directory to: C:\Users\stefanie.meliss\OneDrive - Ambition Institute\code\DfE_data\data\get-information-about-schools

## Yearly School Information

The following variables can be used to identify schools:

**Unique Reference Number (URN)**  
The URN is a sequential and unique number automatically assigned by the DfE’s Get Information about Schools (GIAS) system when a record is created. Children centres are 5 digits and start with a 2. Welsh establishments are 6 digits and start with a 4. All other establishments are 6 digits and start with a 1.
  
**DfE number**  
The DfE number is a concatenation of a **3-digit local authority number** (the local authority that administers the establishment) and a **4-digit establishment number**, usually separated by a slash. This creates a 7-digit number. This number is issued by DfE to all local authority nurseries and compulsory school-aged educational establishments, including further education colleges, that are recorded on Get Information about Schools (GIAS).
  
The DfE number is also known as: 
- The Department for Education number, the Department for Education no, the DfE no;
- the DfE establishment number, the DfE establishment no, the DfE estab number, the DfE estab no;
- the local authority establishment number, the local authority establishment no, the local authority estab number, the local authority estab no;
- the LA establishment number, the LA establishment no, the LA estab number, the LA estab no (however this is one part of the two components that make the DfE number);
- the establishment number, the establishment no, the estab number, the estab no (however this is one part of the two components that make the DfE number).
  
**LAESTAB**  
Local authority establishment. A 3-digit local authority code, followed by a 4-digit establishment code.  

**Local authority number**  
The local authority number is also known as the local authority no, the LA number, the LA no.
The local authority number is a 3 digit number assigned to each local authority.
This number is combined with the 4 digit establishment number to create the 7 digit DfE number


**Establishment number**  
The establishment number is also known as the establishment no, the estab number, the estab no. The establishment number is a 4 digit number.
The number is assigned by the DfE to all local authority nurseries and compulsory school aged educational establishments, including further education colleges, that are recorded on Get Information about Schools (GIAS).
  
**A note on Children’s centres:**  
Children’s centres are included in GIAS for reference and data purposes. However, according to DfE documentation and GIAS, children’s centres do not have an LAESTAB code in the same way as schools and nurseries.
They may have a URN but not always an LAESTAB, because they are not classified as schools or educational establishments for the purposes of DfE funding and reporting.  

For a more detailed explanation on the terms used in the GIAS, please see: https://get-information-schools.service.gov.uk/glossary

In [5]:
# Define the columns to keep and their new names
columns_to_keep = {
        "CensusDate": "Census_Date",
        "URN": "URN", # unique reference number
        "EstablishmentName": "School_Name",
        "LA (code)": "LA_code", # 3-digit LA number
        "EstablishmentNumber": "Estab_Number", # 4-digit estab number
        "LA (name)": "Local_Authority",
        "Postcode": "Postcode",
        "GOR (name)": "Region",
        "UrbanRural (name)": "Urban_Rural",
        "TypeOfEstablishment (name)": "School_Type",
        "EstablishmentTypeGroup (name)": "School_Type_Group",
        "EstablishmentStatus (name)": "School_Status",
        "PhaseOfEducation (name)": "School_Phase",
        "StatutoryLowAge": "School_Age_Low",
        "StatutoryHighAge": "School_Age_High",
        "NurseryProvision (name)": "School_Nursery", 
        "OfficialSixthForm (name)": "School_Sixth_Form",
        "Gender (name)": "School_Gender",
        "ReligiousCharacter (name)": "School_Religious_Character",
        "AdmissionsPolicy (name)": "School_Admissions_Policy",
        "SpecialClasses (name)": "School_Special_Classes",
        "Boarders (name)": "School_Boarders", 
        "SchoolCapacity": "School_Capacity",
        "NumberOfPupils": "School_Number_of_Pupils",
        "PercentageFSM": "School_Percentage_FSM",
        "OpenDate": "School_Open_Date",
        "CloseDate": "School_Close_Date",
        "ReasonEstablishmentOpened (name)": "School_Open_Reason",
        "ReasonEstablishmentClosed (name)": "School_Close_Reason",
        "TrustSchoolFlag (name)": "School_Trust_Flag",
        "Trusts (name)": "School_Trust_Name"
}
print(f"Defined {len(columns_to_keep)} columns to keep")

Defined 31 columns to keep

In [6]:
# DEBUG CODE SNIPPET #

# read in data
tmp = "C:/Users/stefanie.meliss/OneDrive - Ambition Institute/Insights and Data/General/05 Data library/External Data/GIAS/2025-26/edubaseallchildrencentre20251001.csv"
tmp = "C:/Users/stefanie.meliss/OneDrive - Ambition Institute/Insights and Data/General/05 Data library/External Data/GIAS/2025-26/edubasealldata20251001.csv"
df = pd.read_csv(tmp, encoding='latin1', low_memory=False)

# Find which columns are present
available_cols = [col for col in columns_to_keep.keys() if col in df.columns]
print(f"Identified {len(available_cols)} available columns of {len(columns_to_keep)} columns to keep")

# Select and rename available columns
df = df[available_cols].rename(columns={col: columns_to_keep[col] for col in available_cols})

# Add missing columns as NA
for col, new_col in columns_to_keep.items():
    if new_col not in df.columns:
        df[new_col] = pd.NA
df.head()

# Add download date and source file #

# Add source file as column
df["Source_File"] = os.path.basename(tmp)

# Search for an 8-digit number using \d{8} in file name (as extracted from path)
match = re.search(r"(\d{8})", os.path.basename(tmp)) 

# Format date
if match:
    date_str = match.group(1)
    print(f"Extracted date: {date_str}")  # Output: 20211001

    # Convert to a readable date format
    date_obj = datetime.strptime(date_str, "%Y%m%d")
    formatted_date = date_obj.strftime("%d-%m-%Y")
    print(f"Formatted date: {formatted_date}")  # Output: 01-10-2021
else:
    print("No date found in file name.")

# add as column
df["Data_Download_Date"] = pd.to_datetime(formatted_date, format="%d-%m-%Y")

df.head()

Identified 31 available columns of 31 columns to keep
Extracted date: 20251001
Formatted date: 01-10-2025

  Census_Date     URN                      School_Name  LA_code  Estab_Number Local_Authority  Postcode  Region                              Urban_Rural                     School_Type                   School_Type_Group School_Status    School_Phase  School_Age_Low  School_Age_High       School_Nursery           School_Sixth_Form School_Gender School_Religious_Character School_Admissions_Policy School_Special_Classes  School_Boarders  School_Capacity  School_Number_of_Pupils  School_Percentage_FSM School_Open_Date School_Close_Date School_Open_Reason School_Close_Reason School_Trust_Flag School_Trust_Name                 Source_File Data_Download_Date
0  16-01-2025  100000               The Aldgate School      201        3614.0  City of London  EC3A 5DE  London    Urban: Nearer to a major town or city          Voluntary aided school  Local authority maintained schools          Open         Primary             3.0             11.0  Has Nursery Classes  Does not have a sixth form         Mixed          Church of England           Not applicable     No Special Classes      No boarders            245.0                    249.0                   23.3              NaN               NaN     Not applicable      Not applicable    Not applicable               NaN  edubasealldata20251001.csv         2025-10-01
1  18-01-2024  100001  City of London School for Girls      201        6005.0  City of London  EC2Y 8BB  London    Urban: Nearer to a major town or city        Other independent school                 Independent schools          Open  Not applicable            10.0             18.0   No Nursery Classes            Has a sixth form         Girls                        NaN                Selective     No Special Classes      No boarders            860.0                    780.0                    NaN       01-01-1920               NaN     Not applicable      Not applicable    Not applicable               NaN  edubasealldata20251001.csv         2025-10-01
2  18-01-2024  100002       St Paul's Cathedral School      201        6006.0  City of London  EC4M 9AD  London    Urban: Nearer to a major town or city        Other independent school                 Independent schools          Open  Not applicable             4.0             13.0   No Nursery Classes  Does not have a sixth form         Mixed          Church of England           Not applicable     No Special Classes  Boarding school            285.0                    285.0                    NaN       01-01-1939               NaN     Not applicable      Not applicable    Not applicable               NaN  edubasealldata20251001.csv         2025-10-01
3  18-01-2024  100003            City of London School      201        6007.0  City of London  EC4V 3AL  London    Urban: Nearer to a major town or city        Other independent school                 Independent schools          Open  Not applicable            10.0             18.0   No Nursery Classes            Has a sixth form          Boys                        NaN           Not applicable     No Special Classes      No boarders           1100.0                   1074.0                    NaN       01-01-1919               NaN     Not applicable      Not applicable    Not applicable               NaN  edubasealldata20251001.csv         2025-10-01
4         NaN  100004         Sherborne Nursery School      202        1045.0          Camden   NW5 4LP  London  (England/Wales) Urban major conurbation  Local authority nursery school  Local authority maintained schools        Closed         Nursery             3.0              5.0       Not applicable              Not applicable         Mixed             Does not apply           Not applicable         Not applicable      No boarders              NaN                      NaN                    NaN              NaN        31-08-1992     Not applicable      Not applicable    Not applicable               NaN  edubasealldata20251001.csv         2025-10-01

In [7]:
# Combine the edubase data for all years

# Read in Edubase data for all schools 
 # edubaseallchildrencentre accounts for children's centres:
  # no census date
  # no information on school type, phase, number pupils etc.
 # edubasealldata accounts for academies, free schools and state funded schools, but not children's centres

# For each file in the edubase data folder, read it in and combine them all into a single dataframe


# List all files in data directory but keep only directories (folders)
all_items = os.listdir(dir_data)
folders = [item for item in all_items if os.path.isdir(os.path.join(dir_data, item))]

# Get full paths for each folder
edubase_folders = [os.path.join(dir_data, folder) for folder in folders]

# Define an empty list to fill with dataframes
df_list = []

# Loop over folders
for folder in edubase_folders:

    logging.info(f"Current folder: {folder}\n")

    # List all items in the folder
    files = os.listdir(folder)

    # Process links #

    # Select links file
    link_file = [f for f in files if f.startswith('links_edubasealldata') and f.endswith('.csv')]
    link_file = [os.path.join(folder, f) for f in link_file]
    
    # Read in URN links
    urn_links = pd.read_csv(link_file[0], encoding ='latin1')

    # Fix data types
    urn_links["URN"] = urn_links["URN"].astype(str)
    urn_links["LinkURN"] = urn_links["LinkURN"].astype(str)

    # Process information about establishments #

    # Select files that start with 'edubaseall' and end with '.csv', but do not start with 'links_'
    target_files = [f for f in files if f.startswith('edubase') and f.endswith('.csv')]

    # join file name with directory path
    csv_files = [os.path.join(folder, target) for target in target_files]

    # loop over csv files
    for file in csv_files:

        logging.info(f"Reading file: {file}")

        # read in data
        df = pd.read_csv(file, encoding='latin1', low_memory=False)
        
        # Find which columns are present
        available_cols = [col for col in columns_to_keep.keys() if col in df.columns]
        logging.info(f"Identified {len(available_cols)} available columns of {len(columns_to_keep)} columns to keep")

        #  Select and rename available columns
        df = df[available_cols].rename(columns={col: columns_to_keep[col] for col in available_cols})

        # Add missing columns as NA
        for col, new_col in columns_to_keep.items():
            if new_col not in df.columns:
                df[new_col] = pd.NA

        # Add download date and source file #

        # Add source file as column
        df["Source_File"] = os.path.basename(file)

        # Search for an 8-digit number using \d{8} in file name (as extracted from path)
        match = re.search(r"(\d{8})", os.path.basename(file)) 

        # Convert to a readable date format
        if match:
            date_str = match.group(1)
            date_obj = datetime.strptime(date_str, "%Y%m%d")
            formatted_date = date_obj.strftime("%d-%m-%Y")
            logging.info(f"Formatted date: {formatted_date}\n")  # Output: 01-10-2021
        else:
            logging.info("No date found in file name.")

        # add as column
        df["Data_Download_Date"] = pd.to_datetime(formatted_date, format="%d-%m-%Y")

        # add academic year
        academic_year = os.path.basename(folder).replace("-", "")
        df[["Academic_Year"]] = academic_year

        # Reorder columns for consistency
        df = df[["Data_Download_Date"] + ["Academic_Year"] + list(columns_to_keep.values()) + ["Source_File"]]# + ['source_file', 'year_folder']]
        
        # Add to df_list
        df_list.append(df)


# Concatenate all DataFrames
edubase_school_info = pd.concat(df_list, ignore_index=True)

2026-08-20 11:38:20,248 INFO Current folder: C:\Users\stefanie.meliss\OneDrive - Ambition Institute\code\DfE_data\data\get-information-about-schools\2020-21

2026-08-20 11:38:20,573 INFO Reading file: C:\Users\stefanie.meliss\OneDrive - Ambition Institute\code\DfE_data\data\get-information-about-schools\2020-21\edubaseallchildrencentre20210730.csv
2026-08-20 11:38:20,737 INFO Identified 9 available columns of 31 columns to keep
2026-08-20 11:38:20,806 INFO Formatted date: 30-07-2021

2026-08-20 11:38:20,826 INFO Reading file: C:\Users\stefanie.meliss\OneDrive - Ambition Institute\code\DfE_data\data\get-information-about-schools\2020-21\edubasealldata20210730.csv
2026-08-20 11:38:24,237 INFO Identified 31 available columns of 31 columns to keep
2026-08-20 11:38:24,274 INFO Formatted date: 30-07-2021

2026-08-20 11:38:24,283 INFO Current folder: C:\Users\stefanie.meliss\OneDrive - Ambition Institute\code\DfE_data\data\get-information-about-schools\2021-22

2026-08-20 11:38:24,390 INFO Reading file: C:\Users\stefanie.meliss\OneDrive - Ambition Institute\code\DfE_data\data\get-information-about-schools\2021-22\edubaseallchildrencentre20220730.csv
2026-08-20 11:38:24,446 INFO Identified 9 available columns of 31 columns to keep
2026-08-20 11:38:24,464 INFO Formatted date: 30-07-2022

2026-08-20 11:38:24,465 INFO Reading file: C:\Users\stefanie.meliss\OneDrive - Ambition Institute\code\DfE_data\data\get-information-about-schools\2021-22\edubasealldata20220730.csv
2026-08-20 11:38:28,579 INFO Identified 31 available columns of 31 columns to keep
2026-08-20 11:38:28,600 INFO Formatted date: 30-07-2022

2026-08-20 11:38:28,612 INFO Current folder: C:\Users\stefanie.meliss\OneDrive - Ambition Institute\code\DfE_data\data\get-information-about-schools\2022-23

2026-08-20 11:38:28,732 INFO Reading file: C:\Users\stefanie.meliss\OneDrive - Ambition Institute\code\DfE_data\data\get-information-about-schools\2022-23\edubaseallchildrencentre20230730.csv
2026-08-20 11:38:28,801 INFO Identified 9 available columns of 31 columns to keep
2026-08-20 11:38:28,826 INFO Formatted date: 30-07-2023

2026-08-20 11:38:28,834 INFO Reading file: C:\Users\stefanie.meliss\OneDrive - Ambition Institute\code\DfE_data\data\get-information-about-schools\2022-23\edubasealldata20230730.csv
2026-08-20 11:38:31,627 INFO Identified 31 available columns of 31 columns to keep
2026-08-20 11:38:31,648 INFO Formatted date: 30-07-2023

2026-08-20 11:38:31,664 INFO Current folder: C:\Users\stefanie.meliss\OneDrive - Ambition Institute\code\DfE_data\data\get-information-about-schools\2023-24

2026-08-20 11:38:31,792 INFO Reading file: C:\Users\stefanie.meliss\OneDrive - Ambition Institute\code\DfE_data\data\get-information-about-schools\2023-24\edubaseallchildrencentre20240730.csv
2026-08-20 11:38:31,847 INFO Identified 9 available columns of 31 columns to keep
2026-08-20 11:38:31,868 INFO Formatted date: 30-07-2024

2026-08-20 11:38:31,877 INFO Reading file: C:\Users\stefanie.meliss\OneDrive - Ambition Institute\code\DfE_data\data\get-information-about-schools\2023-24\edubasealldata20240730.csv
2026-08-20 11:38:36,143 INFO Identified 31 available columns of 31 columns to keep
2026-08-20 11:38:36,188 INFO Formatted date: 30-07-2024

2026-08-20 11:38:36,197 INFO Current folder: C:\Users\stefanie.meliss\OneDrive - Ambition Institute\code\DfE_data\data\get-information-about-schools\2024-25

2026-08-20 11:38:36,327 INFO Reading file: C:\Users\stefanie.meliss\OneDrive - Ambition Institute\code\DfE_data\data\get-information-about-schools\2024-25\edubaseallchildrencentre20250730.csv
2026-08-20 11:38:36,383 INFO Identified 9 available columns of 31 columns to keep
2026-08-20 11:38:36,405 INFO Formatted date: 30-07-2025

2026-08-20 11:38:36,414 INFO Reading file: C:\Users\stefanie.meliss\OneDrive - Ambition Institute\code\DfE_data\data\get-information-about-schools\2024-25\edubasealldata20250730.csv
2026-08-20 11:38:40,712 INFO Identified 31 available columns of 31 columns to keep
2026-08-20 11:38:40,735 INFO Formatted date: 30-07-2025

2026-08-20 11:38:40,748 INFO Current folder: C:\Users\stefanie.meliss\OneDrive - Ambition Institute\code\DfE_data\data\get-information-about-schools\2025-26

2026-08-20 11:38:40,877 INFO Reading file: C:\Users\stefanie.meliss\OneDrive - Ambition Institute\code\DfE_data\data\get-information-about-schools\2025-26\edubaseallchildrencentre20260820.csv
2026-08-20 11:38:40,930 INFO Identified 9 available columns of 31 columns to keep
2026-08-20 11:38:40,954 INFO Formatted date: 20-08-2026

2026-08-20 11:38:40,964 INFO Reading file: C:\Users\stefanie.meliss\OneDrive - Ambition Institute\code\DfE_data\data\get-information-about-schools\2025-26\edubasealldata20260820.csv
2026-08-20 11:38:45,357 INFO Identified 31 available columns of 31 columns to keep
2026-08-20 11:38:45,376 INFO Formatted date: 20-08-2026

In [8]:
# Show URN links
# this is only the latest links_edubasealldataYYYYMMDD.csv file as this will contain all previous links
urn_links

          URN LinkURN                       LinkName                   LinkType LinkEstablishedDate
0      100006  134643           CCfL Key Stage 3 PRU       Predecessor - merged          01-01-2022
1      100012  100021  Rhyl Community Primary School         Successor - merged          31-08-2021
2      100016  132245       Kingsgate Primary School                  Successor                 NaN
3      100017  132245       Kingsgate Primary School                  Successor                 NaN
4      100021  100012         Carlton Primary School       Predecessor - merged          31-08-2021
...       ...     ...                            ...                        ...                 ...
35232  402491  401325       Llanfabon Infants School                Predecessor          31-03-2026
35233  402492  400225                  Ysgol Y Foryd                Predecessor          31-08-2026
35234  402492  400219                Ysgol Maes Owen                Predecessor          31-08-2026
35235  402493  400220                Ysgol Glan Gele  Predecessor - amalgamated          31-08-2026
35236  402493  400233         St Elfod Junior School  Predecessor - amalgamated          31-08-2026

[35237 rows x 5 columns]

In [9]:
# Show results
edubase_school_info

       Data_Download_Date Academic_Year Census_Date     URN                                                       School_Name  LA_code Estab_Number    Local_Authority  Postcode           Region                               Urban_Rural          School_Type School_Type_Group     School_Status    School_Phase School_Age_Low School_Age_High  School_Nursery School_Sixth_Form School_Gender School_Religious_Character School_Admissions_Policy School_Special_Classes School_Boarders School_Capacity School_Number_of_Pupils School_Percentage_FSM School_Open_Date School_Close_Date      School_Open_Reason School_Close_Reason School_Trust_Flag School_Trust_Name                           Source_File
0              2021-07-30        202021        <NA>   20001                                    The Starship Children's Centre      873         <NA>     Cambridgeshire  CB23 8DY  East of England                                      <NA>    Children's centre              <NA>              Open            <NA>           <NA>            <NA>            <NA>              <NA>          <NA>                       <NA>                     <NA>                   <NA>            <NA>            <NA>                    <NA>                  <NA>       18-12-2009              <NA>                    <NA>                <NA>              <NA>              <NA>  edubaseallchildrencentre20210730.csv
1              2021-07-30        202021        <NA>   20002  Carlisle South Petteril Bank Upperby SureStart Children's Centre      909         <NA>            Cumbria   CA1 3BX       North West                                      <NA>    Children's centre              <NA>              Open            <NA>           <NA>            <NA>            <NA>              <NA>          <NA>                       <NA>                     <NA>                   <NA>            <NA>            <NA>                    <NA>                  <NA>       21-01-2005              <NA>                    <NA>                <NA>              <NA>              <NA>  edubaseallchildrencentre20210730.csv
2              2021-07-30        202021        <NA>   20003                              Central Sure Start Children's Centre      852         <NA>        Southampton  SO14 0AU       South East                                      <NA>    Children's centre              <NA>              Open            <NA>           <NA>            <NA>            <NA>              <NA>          <NA>                       <NA>                     <NA>                   <NA>            <NA>            <NA>                    <NA>                  <NA>       28-03-2006              <NA>                    <NA>                <NA>              <NA>              <NA>  edubaseallchildrencentre20210730.csv
3              2021-07-30        202021        <NA>   20004                                            Ryde Children's Centre      921         <NA>      Isle of Wight  PO33 2JF       South East                                      <NA>    Children's centre              <NA>              Open            <NA>           <NA>            <NA>            <NA>              <NA>          <NA>                       <NA>                     <NA>                   <NA>            <NA>            <NA>                    <NA>                  <NA>       19-10-2005              <NA>                    <NA>                <NA>              <NA>              <NA>  edubaseallchildrencentre20210730.csv
4              2021-07-30        202021        <NA>   20006                        West Allerdale SureStart Children's Centre      909         <NA>            Cumbria  CA15 8HN       North West                                      <NA>    Children's centre              <NA>              Open            <NA>           <NA>            <NA>            <NA>              <NA>          <NA>                       <NA>                     <NA>                   <NA>            <NA>            <NA>                    <NA>                  <NA>       28-03-2006              <NA>                    <NA>                <NA>              <NA>              <NA>  edubaseallchildrencentre20210730.csv
...                   ...           ...         ...     ...                                                               ...      ...          ...                ...       ...              ...                                       ...                  ...               ...               ...             ...            ...             ...             ...               ...           ...                        ...                      ...                    ...             ...             ...                     ...                   ...              ...               ...                     ...                 ...               ...               ...                                   ...
321922         2026-08-20        202526         NaN  402490                                           Ysgol Gynradd Glyn-coch      674       2389.0  Rhondda Cynon Taf  CF37 3BP   Wales (pseudo)     Urban: Nearer to a major town or city  Welsh establishment     Welsh schools  Proposed to open  Not applicable            NaN             NaN  Not applicable    Not applicable           NaN                        NaN                      NaN         Not applicable             NaN             NaN                     NaN                   NaN       01-09-2026               NaN                     NaN                 NaN    Not applicable               NaN            edubasealldata20260820.csv
321923         2026-08-20        202526         NaN  402491                                             Nelson Primary School      676       2397.0         Caerphilly  CF46 6HL   Wales (pseudo)     Urban: Nearer to a major town or city  Welsh establishment     Welsh schools              Open  Not applicable            NaN             NaN  Not applicable    Not applicable           NaN                        NaN                      NaN         Not applicable             NaN             NaN                     NaN                   NaN       01-04-2026               NaN  Result of Amalgamation                 NaN    Not applicable               NaN            edubasealldata20260820.csv
321924         2026-08-20        202526         NaN  402492                                                  Ysgol Awel y Môr      662       2277.0              Conwy  LL18 5LE   Wales (pseudo)  Urban: Further from a major town or city  Welsh establishment     Welsh schools  Proposed to open  Not applicable            NaN             NaN  Not applicable    Not applicable           NaN                        NaN                      NaN         Not applicable             NaN             NaN                     NaN                   NaN       01-09-2026               NaN  Result of Amalgamation                 NaN    Not applicable               NaN            edubasealldata20260820.csv
321925         2026-08-20        202526         NaN  402493                                                  Ysgol Tan y Gopa      662       2278.0              Conwy  LL22 7NU   Wales (pseudo)  Urban: Further from a major town or city  Welsh establishment     Welsh schools  Proposed to open  Not applicable            NaN             NaN  Not applicable    Not applicable           NaN                        NaN                      NaN         Not applicable             NaN             NaN                     NaN                   NaN       01-09-2026               NaN  Result of Amalgamation                 NaN    Not applicable               NaN            edubasealldata20260820.csv
321926         2026-08-20        202526         NaN  402494                                                          Cwm Alun      665       1106.0            Wrexham  LL11 4NT   Wales (pseudo)     Urban: Nearer to a major town or city  Welsh establishment     Welsh schools  Proposed to open  Not applicable            NaN             NaN  Not applicable    Not applicable           NaN                        NaN                      NaN         Not applicable             NaN             NaN                     NaN                   NaN       01-09-2026               NaN                     NaN                 NaN    Not applicable               NaN            edubasealldata20260820.csv

[321927 rows x 34 columns]

In [10]:
# Get data types
edubase_school_info.dtypes

Data_Download_Date            datetime64[us]
Academic_Year                            str
Census_Date                           object
URN                                    int64
School_Name                              str
LA_code                                int64
Estab_Number                          object
Local_Authority                          str
Postcode                                 str
Region                                   str
Urban_Rural                           object
School_Type                              str
School_Type_Group                     object
School_Status                            str
School_Phase                          object
School_Age_Low                        object
School_Age_High                       object
School_Nursery                        object
School_Sixth_Form                     object
School_Gender                         object
School_Religious_Character            object
School_Admissions_Policy              object
School_Special_Classes                object
School_Boarders                       object
School_Capacity                       object
School_Number_of_Pupils               object
School_Percentage_FSM                 object
School_Open_Date                         str
School_Close_Date                     object
School_Open_Reason                    object
School_Close_Reason                   object
School_Trust_Flag                     object
School_Trust_Name                     object
Source_File                              str
dtype: object

In [11]:
# Sort out and dtypes and any other data cleaning

# Set datetimes
edubase_school_info["Census_Date"] = pd.to_datetime(edubase_school_info["Census_Date"], format="%d-%m-%Y", errors='coerce')
edubase_school_info["School_Open_Date"] = pd.to_datetime(edubase_school_info["School_Open_Date"], format="%d-%m-%Y", errors='coerce')
edubase_school_info["School_Close_Date"] = pd.to_datetime(edubase_school_info["School_Close_Date"], format="%d-%m-%Y", errors='coerce')

# Set other dtypes
edubase_school_info = edubase_school_info.astype({
    "URN": str,
    "LA_code": 'Int64',
    "Estab_Number": 'Int64',
    "School_Age_Low": 'Int64',
    "School_Age_High": 'Int64',
    "School_Capacity": 'Int64',
    "School_Number_of_Pupils": 'Int64',
    "School_Percentage_FSM": 'Float64'
})

# Convert columns to pandas’ nullable string type
for col in edubase_school_info.columns:
    if edubase_school_info[col].dtype == 'object':
        edubase_school_info[col] = edubase_school_info[col].astype('string')

In [12]:
# Create LAESTAB and DfE_Number
def make_laestab(row):
    if pd.notna(row['LA_code']) and pd.notna(row['Estab_Number']):
        return f"{int(row['LA_code']):03d}{int(row['Estab_Number']):04d}"
    else:
        return pd.NA
        
def make_dfe_number(row):
    if pd.notna(row['LA_code']) and pd.notna(row['Estab_Number']):
        return f"{int(row['LA_code']):03d}/{int(row['Estab_Number']):04d}"
    else:
        return pd.NA

# Apply functions to create new columns
edubase_school_info['LAESTAB'] = edubase_school_info.apply(make_laestab, axis=1).astype('string')
edubase_school_info['DfE_Number'] = edubase_school_info.apply(make_dfe_number, axis=1).astype('string')

# Reorder columns for consistency
edubase_school_info = edubase_school_info[["Data_Download_Date"] + ["Academic_Year"] + ["LAESTAB"] + ["DfE_Number"] + list(columns_to_keep.values()) + ["Source_File"]]

In [13]:
# Check unique values of each column to spot any unstandardised values
for col in edubase_school_info.columns:
    print(col, edubase_school_info[col].unique())

Data_Download_Date <DatetimeArray>
['2021-07-30 00:00:00', '2022-07-30 00:00:00', '2023-07-30 00:00:00', '2024-07-30 00:00:00', '2025-07-30 00:00:00', '2026-08-20 00:00:00']
Length: 6, dtype: datetime64[us]
Academic_Year <ArrowStringArray>
['202021', '202122', '202223', '202324', '202425', '202526']
Length: 6, dtype: str
LAESTAB <ArrowStringArray>
[     <NA>, '2013614', '2016005', '2016006', '2016007', '2021045', '2021048', '2021100', '2021101', '2022019',
 ...
 '6661104', '6691113', '6657019', '6802332', '6747016', '6742389', '6762397', '6622277', '6622278', '6651106']
Length: 44543, dtype: string
DfE_Number <ArrowStringArray>
[      <NA>, '201/3614', '201/6005', '201/6006', '201/6007', '202/1045', '202/1048', '202/1100', '202/1101', '202/2019',
 ...
 '666/1104', '669/1113', '665/7019', '680/2332', '674/7016', '674/2389', '676/2397', '662/2277', '662/2278', '665/1106']
Length: 44543, dtype: string
Census_Date <DatetimeArray>
['NaT', '2021-01-21 00:00:00', '2019-01-17 00:00:00', '2018-01-18 00:00:00', '2017-01-19 00:00:00', '2020-01-16 00:00:00', '2022-01-20 00:00:00', '2024-01-18 00:00:00', '2023-01-19 00:00:00', '2025-01-16 00:00:00', '2026-01-15 00:00:00']
Length: 11, dtype: datetime64[us]
URN <ArrowStringArray>
[ '20001',  '20002',  '20003',  '20004',  '20006',  '20007',  '20008',  '20009',  '20010',  '20011',
 ...
 '402485', '402486', '402487', '402488', '402489', '402490', '402491', '402492', '402493', '402494']
Length: 55532, dtype: str
School_Name <ArrowStringArray>
[                                  'The Starship Children's Centre', 'Carlisle South Petteril Bank Upperby SureStart Children's Centre',                             'Central Sure Start Children's Centre',                                           'Ryde Children's Centre',                       'West Allerdale SureStart Children's Centre',                                             '1a Children's Centre',                           '1st Place Children and Parents' Centre',                                 '3R1 Abbots Langley Family Centre',                                  '3R2 Croxley Green Family Centre',                                  '3R3 Rickmansworth Family Centre',
 ...
                                  'North Powys Pupil Referral Unit',                                  'South Powys Pupil Referral Unit',                                                  'Canolfan Y Gors',                                              'Copa Special School',                                     'Pont y Gamlas Primary School',                                                   'Ysgol Cambrian',                                          'Ysgol Gynradd Glyn-coch',                                                 'Ysgol Awel y Môr',                                                 'Ysgol Tan y Gopa',                                                         'Cwm Alun']
Length: 46927, dtype: str
LA_code <IntegerArray>
[873, 909, 852, 921, 202, 210, 919, 356, 891, 315,
 ...
 660, 661, 662, 663, 666, 667, 668, 671, 942, 943]
Length: 188, dtype: Int64
Estab_Number <IntegerArray>
[<NA>, 3614, 6005, 6006, 6007, 1045, 1048, 1100, 1101, 2019,
 ...
 5506, 7920, 7921, 6416, 7922, 6423, 6424, 6426, 6427, 6428]
Length: 3741, dtype: Int64
Local_Authority <ArrowStringArray>
[         'Cambridgeshire',                 'Cumbria',             'Southampton',           'Isle of Wight',                  'Camden',               'Southwark',           'Hertfordshire',               'Stockport',         'Nottinghamshire',                  'Merton',
 ...
                 'Gwynedd',                   'Conwy',            'Denbighshire',                   'Powys',              'Ceredigion',           'Pembrokeshire',       'Neath Port Talbot',              'Cumberland', 'Westmorland and Furness',    'Pre-LGR 2023 Cumbria']
Length: 189, dtype: str
Postcode <ArrowStringArray>
['CB23 8DY',  'CA1 3BX', 'SO14 0AU', 'PO33 2JF', 'CA15 8HN', 'EC1R 4SR',  'SE5 0RN',  'WD5 0LB',  'WD3 3PX',  'WD3 8JJ',
 ...
 'CF38 2SE', 'NP19 9QP', 'NP19 9LU', 'NP10 8AT', 'NP16 6DF', 'NP19 7HF',  'SA9 2DY', 'SA15 4BG', 'LL14 3US', 'CF40 2XX']
Length: 33630, dtype: str
Region <ArrowStringArray>
['East of England', 'North West', 'South East', 'London', 'East Midlands', 'Yorkshire and the Humber', 'South West', 'North East', 'West Midlands', 'Wales (pseudo)', 'Not Applicable']
Length: 11, dtype: str
Urban_Rural <ArrowStringArray>
[<NA>, '(England/Wales) Urban major conurbation', '(England/Wales) Urban city and town', '(England/Wales) Rural hamlet and isolated dwellings', '(England/Wales) Rural town and fringe', '(England/Wales) Rural village', '(England/Wales) Urban minor conurbation', '(England/Wales) Rural village in a sparse setting', '(England/Wales) Rural hamlet and isolated dwellings in a sparse setting', '(England/Wales) Urban city and town in a sparse setting', '(England/Wales) Rural town and fringe in a sparse setting', '(pseudo) Channel Islands/Isle of Man', '(Scotland) Other Urban Area', '(Scotland) Remote Small Town', '(Scotland) Accessible Rural', '(Scotland) Large Urban Area', '(Scotland) Remote Rural', 'Urban: Nearer to a major town or city', 'Urban: Further from a major town or city', 'Smaller rural: Nearer to a major town or city', 'Larger rural: Nearer to a major town or city', 'Larger rural: Further from a major town or city', 'Smaller rural: Further from a major town or city', '(Scotland) Accessible Small Town', '(Scotland) Very Remote Small Town']
Length: 25, dtype: string
School_Type <ArrowStringArray>
['Children's centre', 'Children's centre linked site', 'Voluntary aided school', 'Other independent school', 'Local authority nursery school', 'Pupil referral unit', 'Community school', 'Foundation special school', 'Community special school', 'Foundation school', 'Voluntary controlled school', 'City technology college', 'Other independent special school', 'Non-maintained special school', 'Academy sponsor led', 'Miscellaneous', 'Special post 16 institution', 'Further education', 'Secure units', 'Higher education institutions', 'Institution funded by other government department', 'Service children's education', 'British schools overseas', 'Offshore schools', 'Sixth form centres', 'Academy converter', 'Free schools', 'University technical college', 'Academy special converter', 'Studio schools', 'Academy alternative provision sponsor led', 'Academy special sponsor led', 'Free schools alternative provision', 'Free schools special', 'Free schools 16 to 19', 'Academy 16-19 converter', 'Academy alternative provision converter', 'Academy 16 to 19 sponsor led', 'Welsh establishment', 'Online provider', 'Academy secure 16 to 19']
Length: 41, dtype: str
School_Type_Group <ArrowStringArray>
[<NA>, 'Local authority maintained schools', 'Independent schools', 'Special schools', 'Academies', 'Other types', 'Colleges', 'Universities', 'Free Schools', 'Welsh schools', 'Online provider']
Length: 11, dtype: string
School_Status <ArrowStringArray>
['Open', 'Closed', 'Open, but proposed to close', 'Proposed to open']
Length: 4, dtype: str
School_Phase <ArrowStringArray>
[<NA>, 'Primary', 'Not applicable', 'Nursery', 'Secondary', 'All-through', 'Middle deemed secondary', 'Middle deemed primary', '16 plus']
Length: 9, dtype: string
School_Age_Low <IntegerArray>
[<NA>, 3, 7, 4, 10, 14, 5, 2, 11, 13, 9, 15, 1, 6, 16, 0, 8, 12, 18, 19, 17]
Length: 21, dtype: Int64
School_Age_High <IntegerArray>
[<NA>, 11, 18, 13, 5, 16, 7, 8, 19, 12, 4, 21, 14, 17, 15, 6, 25, 20, 22, 10, 9, 23, 24, 28, 99, 3, 30, 60, 35, 45, 0]
Length: 31, dtype: Int64
School_Nursery <ArrowStringArray>
[<NA>, 'Has Nursery Classes', 'No Nursery Classes', 'Not applicable']
Length: 4, dtype: string
School_Sixth_Form <ArrowStringArray>
[<NA>, 'Does not have a sixth form', 'Has a sixth form', 'Not applicable']
Length: 4, dtype: string
School_Gender <ArrowStringArray>
[<NA>, 'Mixed', 'Girls', 'Boys', 'Not applicable']
Length: 5, dtype: string
School_Religious_Character <ArrowStringArray>
[<NA>, 'Church of England', 'Does not apply', 'Roman Catholic', 'Catholic', 'Jewish', 'Charadi Jewish', 'Islam', 'Christian', 'Anglican', 'Orthodox Jewish', 'Muslim', 'Hindu', 'Methodist', 'Free Church', 'Church of England/Christian', 'Seventh Day Adventist', 'Church of England/Methodist', 'Congregational Church', 'Church of England/Free Church', 'Christian/Evangelical', 'Protestant/Evangelical', 'Church of England/Roman Catholic', 'Moravian', 'Quaker', 'United Reformed Church', 'Anglican/Evangelical', 'Church of England/Evangelical', 'Christian/Methodist', 'Roman Catholic/Church of England', 'Anglican/Christian', 'Roman Catholic/Anglican', 'Anglican/Church of England', 'Buddhist', 'Christian/non-denominational', 'Protestant', 'Christian Science', 'Church of England/United Reformed Church', 'Reformed Baptist', 'Sikh', 'Greek Orthodox', 'Inter- / non- denominational', 'Church of England/Methodist/United Reform Church/Baptist', 'Plymouth Brethren Christian Church', 'Sunni Deobandi', 'Multi-faith', 'Methodist/Church of England']
Length: 47, dtype: string
School_Admissions_Policy <ArrowStringArray>
[<NA>, 'Not applicable', 'Non-selective', 'Selective']
Length: 4, dtype: string
School_Special_Classes <ArrowStringArray>
[<NA>, 'No Special Classes', 'Not applicable', 'Has Special Classes']
Length: 4, dtype: string
School_Boarders <ArrowStringArray>
[<NA>, 'No boarders', 'Boarding school', 'Children's home (Boarding school)', 'Not applicable', 'College / FE residential accommodation']
Length: 6, dtype: string
School_Capacity <IntegerArray>
[<NA>,  276,  780,  265, 1040,   20,  432,  459,  583,  436,
 ...
 1899, 1902, 2830, 2420, 1699, 1586, 1388, 2243, 2290, 1576]
Length: 1886, dtype: Int64
School_Number_of_Pupils <IntegerArray>
[<NA>,  270,  769,  241,  991,  114,   37,   17,  335,  418,
 ...
 2799, 2615, 2568, 2404, 1866, 2485, 1939, 2104, 2161, 1793]
Length: 2200, dtype: Int64
School_Percentage_FSM <FloatingArray>
[<NA>, 13.7,  0.0, 37.2, 56.8, 94.1, 51.9, 38.5, 49.1, 21.2,
 ...
 89.8, 89.7, 91.1, 91.9, 77.6, 84.0, 97.6, 91.7, 85.6, 94.7]
Length: 896, dtype: Float64
School_Open_Date <DatetimeArray>
['2009-12-18 00:00:00', '2005-01-21 00:00:00', '2006-03-28 00:00:00', '2005-10-19 00:00:00', '2007-09-06 00:00:00', '2006-01-24 00:00:00', '2009-12-01 00:00:00', '2010-02-23 00:00:00', '2007-11-07 00:00:00', '2007-09-27 00:00:00',
 ...
 '2027-10-01 00:00:00', '2026-08-05 00:00:00', '2026-01-29 00:00:00', '2026-07-08 00:00:00', '2026-07-28 00:00:00', '2026-08-13 00:00:00', '2026-03-26 00:00:00', '2026-03-05 00:00:00', '2026-06-24 00:00:00', '2026-06-10 00:00:00']
Length: 3728, dtype: datetime64[us]
School_Close_Date <DatetimeArray>
[                'NaT', '1992-08-31 00:00:00', '2021-08-31 00:00:00', '2000-08-31 00:00:00', '2015-09-11 00:00:00', '2019-12-31 00:00:00', '2016-12-31 00:00:00', '1998-07-31 00:00:00', '1999-03-16 00:00:00', '2013-04-24 00:00:00',
 ...
 '2026-07-21 00:00:00', '2025-07-23 00:00:00', '2025-11-13 00:00:00', '2023-10-23 00:00:00', '2025-08-06 00:00:00', '2026-02-01 00:00:00', '2026-02-02 00:00:00', '2025-09-18 00:00:00', '2026-02-26 00:00:00', '2025-02-03 00:00:00']
Length: 2638, dtype: datetime64[us]
School_Open_Reason <ArrowStringArray>
[<NA>, 'Not applicable', 'Result of Amalgamation', 'Result of Closure', 'New Provision', 'Not Recorded', 'Fresh Start', 'Change in status', 'New Nursery School', 'Change Religious Character', 'Former Independent', 'Academy Free School', 'Academy Converter', 'Free Special School', 'Split school', 'Meets accreditation standards']
Length: 16, dtype: string
School_Close_Reason <ArrowStringArray>
[<NA>, 'Not applicable', 'Result of Amalgamation/Merger', 'Closure', 'Close Nursery School', 'Academy Converter', 'Fresh Start', 'For Academy', 'Academy Free School', 'Change Religious Character', 'Does not meet criteria for registration', 'Change in status', 'De-registered', 'Transferred to new sponsor', 'Created in Error - application rejected']
Length: 15, dtype: string
School_Trust_Flag <ArrowStringArray>
[<NA>, 'Not applicable', 'Not supported by a trust', 'Supported by a trust', 'Supported by a single-academy trust', 'Supported by a multi-academy trust']
Length: 6, dtype: string
School_Trust_Name <ArrowStringArray>
[                                                 <NA>,                           'Eltham Green School Trust', '*Co-op Brent Knoll and Watergate Co-operative Trust',                      'The Academies Enterprise Trust',              'The Copland Learning Partnership Trust',       'Aspiration for All Co-Operative Trust (AFACT)',                               'The Bourne Foundation',                        'Enterprise Cooperative Trust',            'The Victoria Co-operative Learning Trust',                              'Sutton Education Trust',
 ...
                         'RESPECT COLLABORATION TRUST',                              'SUMMIT EDUCATION TRUST',       'EMMANUEL DIOCESE OF LIVERPOOL ACADEMIES TRUST',                            'THE WULFRUNA PARTNERSHIP',                      'LIGHTHOUSE MULTI ACADEMY TRUST',                       'BELONG CE MULTI ACADEMY TRUST',                              'FRANKLIN COLLEGE TRUST',                       'HILLS EDUCATION TRUST LIMITED',                     'CHESTER DIOCESAN LEARNING TRUST',                     'ST CARLO CATHOLIC ACADEMY TRUST']
Length: 3107, dtype: string
Source_File <ArrowStringArray>
['edubaseallchildrencentre20210730.csv', 'edubasealldata20210730.csv', 'edubaseallchildrencentre20220730.csv', 'edubasealldata20220730.csv', 'edubaseallchildrencentre20230730.csv', 'edubasealldata20230730.csv', 'edubaseallchildrencentre20240730.csv', 'edubasealldata20240730.csv', 'edubaseallchildrencentre20250730.csv', 'edubasealldata20250730.csv', 'edubaseallchildrencentre20260820.csv', 'edubasealldata20260820.csv']
Length: 12, dtype: str

In [14]:
# List of possible unstandardised NA values
unstandardised_na_values = ['', 'NA', 'N/A', 'null', 'None', 'NaN', 'nan', 'none']

# Dictionary to store columns with unstandardised NA values
cols_with_unstandardised_na = {}

for col in edubase_school_info.columns:
    # Only check object (string) columns
    if edubase_school_info[col].dtype == 'object':
        # Count cells with unstandardised NA values
        mask = edubase_school_info[col].isin(unstandardised_na_values)
        count = mask.sum()
        if count > 0:
            cols_with_unstandardised_na[col] = count

print("Columns with unstandardised NA values:", cols_with_unstandardised_na)

# Sort out the <NA> values
if len(cols_with_unstandardised_na) > 0:
    for col in cols_with_unstandardised_na:
        edubase_school_info[col] = edubase_school_info[col].fillna(np.nan)
else:
    print("No columns with unstandardised NA values found.")

Columns with unstandardised NA values: {}
No columns with unstandardised NA values found.

In [15]:
# Assess data

# Count nulls in each column
percent_nulls = (edubase_school_info.isnull().mean() * 100).round(2)

print(percent_nulls)

Data_Download_Date             0.00
Academic_Year                  0.00
LAESTAB                        5.66
DfE_Number                     5.66
Census_Date                   45.19
URN                            0.00
School_Name                    0.00
LA_code                        0.00
Estab_Number                   5.66
Local_Authority                0.00
Postcode                       2.64
Region                         0.00
Urban_Rural                    8.05
School_Type                    0.00
School_Type_Group              5.40
School_Status                  0.00
School_Phase                   5.40
School_Age_Low                12.80
School_Age_High               12.79
School_Nursery                 5.46
School_Sixth_Form              5.42
School_Gender                  8.05
School_Religious_Character    28.48
School_Admissions_Policy      15.21
School_Special_Classes         5.63
School_Boarders                8.35
School_Capacity               28.36
School_Number_of_Pupils       45.22
School_Percentage_FSM         48.11
School_Open_Date              57.81
School_Close_Date             56.57
School_Open_Reason             6.69
School_Close_Reason           29.03
School_Trust_Flag              5.40
School_Trust_Name             78.97
Source_File                    0.00
dtype: float64

#### Output

Save the new data

In [17]:
# save csv file
dir_out = home / 'OneDrive - Ambition Institute' / 'code' / 'DfE_data' / 'data'
os.chdir(dir_out)

edubase_school_info.to_csv("data_gias_estab_pa.csv", index=False)